version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: "null"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "null"
  open-pull-requests-limit: 10
